### ISSUE TITLE
scrollbar shouldn't depend on .js

### ISSUE THREAD

**Issue by tarzanek** [OpenGrok/OpenGrok#1488]
When loading big file firefox won't print its scrollbar
due to .js errors

content shouldn't depend on .js to show

.js needs to be loaded at the end of the page

**Comment by ilovemaui** [comment]
how long to fix this? and is this a complete rebuild? or is there a quick way to fix?

**Comment by vladak** [comment]
According to @tulinkry there is fair amount of work associated with this change. Given the relatively low impact and impending release I am removing the stopper keyword.

**Comment by stevenschlansker** [comment]
The original issue description isn't very precise, so I'm not sure if this is the same problem -- but we are noticing that our javascript files on the source viewer have an incorrect relative path.

e.g. the page `http://opengrok/xref/myproj/src/main.c` has this block at the bottom of the page:
```
	<script type="text/javascript" src="js/jquery-3.2.0.min.js" data-priority="10"></script>
	<script type="text/javascript" src="js/jquery-ui-1.12.0-custom.min.js" data-priority="11"></script>
	<script type="text/javascript" src="js/jquery-tablesorter-2.26.6.min.js" data-priority="12"></script>
	<script type="text/javascript" src="js/tablesorter-parsers-0.0.1.js" data-priority="13"></script>
	<script type="text/javascript" src="js/searchable-option-list-2.0.3.min.js" data-priority="14"></script>
	<script type="text/javascript" src="js/utils-0.0.9.js" data-priority="15"></script>
```
which is relative to the *project directory of the source being viewed* instead of the context root, which the code in [Scripts.java](https://github.com/OpenGrok/OpenGrok/blob/master/src/org/opensolaris/opengrok/web/Scripts.java#L116-L131) assumes.

Is this the issue reported above, or should I open a new issue report?  This causes any source file longer than a page to be inaccessible so I'd consider it probably a blocker.  Confirmed that the behavior is browser independent and affects OpenGrok 0.13 (is that the same as 1.0?)

**Comment by vladak** [comment]
yep, 0.13 was renamed to 1.0 just before the release.

**Comment by stevenschlansker** [comment]
Any comment on whether this is the same issue or I should open a new one?

**Comment by vladak** [comment]
@stevenschlansker im the recent `master` branch (1.1-rc5+) I see this in the web page source when requesting content under `/source/xref/`:

```
<script type="text/javascript" src="/source/js/jquery-3.2.0.min.js" data-priority="10"></script>
	<script type="text/javascript" src="/source/js/jquery-ui-1.12.0-custom.min.js" data-priority="11"></script>
	<script type="text/javascript" src="/source/js/jquery-tablesorter-2.26.6.min.js" data-priority="12"></script>
	<script type="text/javascript" src="/source/js/tablesorter-parsers-0.0.1.js" data-priority="13"></script>
	<script type="text/javascript" src="/source/js/searchable-option-list-2.0.3.min.js" data-priority="14"></script>
	<script type="text/javascript" src="/source/js/utils-0.0.9.js" data-priority="15"></script>
```

**Comment by tulinkry** [comment]
It's not the same problem, I've seen an issue related to this but I can't find it now.

**Comment by stevenschlansker** [comment]
Okay, sounds like it is fixed for the next release anyway.  Thanks for looking and sorry to hijack this thread.

**Comment by tulinkry** [comment]
Your problem is not fixed actually however you'll be able to scroll with the new fix
